import 'package:base_flutter/customer/models/CategoryModel.dart';
import 'package:base_flutter/customer/models/Dtos/HomeMainModel.dart';
import 'package:base_flutter/customer/models/sub_category_model.dart';
import 'package:base_flutter/customer/resources/CustomerRepoImports.dart';
import 'package:base_flutter/customer/screens/home/tabs_color_cubit/tabs_color_cubit.dart';
import 'package:base_flutter/customer/widgets/LinearContainer.dart';
import 'package:base_flutter/general/blocks/generic_cubit/generic_cubit.dart';
import 'package:base_flutter/general/constants/MyColors.dart';
import 'package:base_flutter/general/utilities/localization/LocalizationMethods.dart';
import 'package:base_flutter/general/widgets/DefaultAppBar.dart';
import 'package:base_flutter/general/widgets/GenericListView.dart';
import 'package:base_flutter/general/widgets/MyText.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'widgets/HomeMainWidgetImports.dart';

part 'HomeMain.dart';
part 'HomeMainData.dart';